name: test-dev-junior
main: com.onyell.Main
version: 1.0
api-version: 1.21
commands:
  home:
    description: Teleporta o jogador para sua home.
  sethome:
    description: Define a home do jogador.
  reloadconfig:
    description: Recarrega a configuração do plugin.
  homelist:
    description: Lista todos as homes.
  homeremove:
    description: Remove alguma home.